name: 'Test Report'
on:
  workflow_run:
    workflows: ['Test']
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  test-report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results            # artifact name
          name: Tests results                  # Name of the check run which will be created
          path: '*.xml'                     # Path to test results (inside artifact .zip)
          reporter: jest-junit            # Format of test results


  coverage-report:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v7
        continue-on-error: true
        with:
          workflow: test.yml # this file
          workflow_conclusion: success
          check_artifacts: true
          branch: master
          name: coverage-report
          path: old-coverage

      - name: Coverage Report as Comment (Clover)
        uses: lucassabreu/comment-coverage-clover@main
        with:
          file: coverage.xml
          base-file: old-coverage/coverage.xml